<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>name</key>
    <string>StrupatForm</string>
    <key>scopeName</key>
    <string>source.sf</string>
    <key>fileTypes</key>
    <array>
        <string>sf</string>
    </array>
    <key>patterns</key>
    <array>
        <dict>
            <key>include</key>
            <string>#rule-definition-inline</string>
        </dict>
        <dict>
            <key>include</key>
            <string>#rule-definition-heading</string>
        </dict>
        <dict>
            <key>include</key>
            <string>#indented-alternative</string>
        </dict>
    </array>
    <key>repository</key>
    <dict>
        <key>rule-definition-inline</key>
        <dict>
            <key>match</key>
            <string>^([A-Za-z_]\w*)(\s+-&gt;\s+)(.*)</string>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.type.rule.sf</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>keyword.operator.arrow.sf</string>
                </dict>
                <key>3</key>
                <dict>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>#alternative</string>
                        </dict>
                    </array>
                </dict>
            </dict>
        </dict>
        <key>rule-definition-heading</key>
        <dict>
            <key>match</key>
            <string>^([A-Za-z_]\w*)\s*$</string>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.type.rule.sf</string>
                </dict>
            </dict>
        </dict>
        <key>indented-alternative</key>
        <dict>
            <key>match</key>
            <string>^(?:\t|    )(.+)</string>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>#alternative</string>
                        </dict>
                    </array>
                </dict>
            </dict>
        </dict>
        <key>alternative</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#string-literal</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#char-literal</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#character-class</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#arrow-operator</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#quantifier</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#group-parens</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#rule-reference</string>
                </dict>
            </array>
        </dict>
        <key>arrow-operator</key>
        <dict>
            <key>match</key>
            <string>-&gt;</string>
            <key>name</key>
            <string>keyword.operator.arrow.sf</string>
        </dict>
        <key>string-literal</key>
        <dict>
            <key>begin</key>
            <string>"</string>
            <key>end</key>
            <string>"</string>
            <key>name</key>
            <string>string.quoted.double.sf</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#escape-sequence</string>
                </dict>
            </array>
        </dict>
        <key>char-literal</key>
        <dict>
            <key>begin</key>
            <string>'</string>
            <key>end</key>
            <string>'</string>
            <key>name</key>
            <string>string.quoted.single.sf</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#escape-sequence</string>
                </dict>
            </array>
        </dict>
        <key>escape-sequence</key>
        <dict>
            <key>match</key>
            <string>\\[0\\tnr"']</string>
            <key>name</key>
            <string>constant.character.escape.sf</string>
        </dict>
        <key>character-class</key>
        <dict>
            <key>begin</key>
            <string>\[</string>
            <key>end</key>
            <string>\]</string>
            <key>beginCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.character-class.begin.sf</string>
                </dict>
            </dict>
            <key>endCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.character-class.end.sf</string>
                </dict>
            </dict>
            <key>name</key>
            <string>constant.other.character-class.sf</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>match</key>
                    <string>\^</string>
                    <key>name</key>
                    <string>keyword.operator.negation.sf</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>\\[wWdDsS]</string>
                    <key>name</key>
                    <string>constant.character.escape.shorthand.sf</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>\\[^\n]</string>
                    <key>name</key>
                    <string>constant.character.escape.sf</string>
                </dict>
            </array>
        </dict>
        <key>quantifier</key>
        <dict>
            <key>match</key>
            <string>[?*+]</string>
            <key>name</key>
            <string>keyword.operator.quantifier.sf</string>
        </dict>
        <key>group-parens</key>
        <dict>
            <key>begin</key>
            <string>\(</string>
            <key>end</key>
            <string>\)</string>
            <key>beginCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.section.group.begin.sf</string>
                </dict>
            </dict>
            <key>endCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.section.group.end.sf</string>
                </dict>
            </dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#alternative</string>
                </dict>
            </array>
        </dict>
        <key>rule-reference</key>
        <dict>
            <key>match</key>
            <string>[A-Za-z_]\w*</string>
            <key>name</key>
            <string>variable.other.rule-reference.sf</string>
        </dict>
    </dict>
</dict>
</plist>