<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<RootNamespace>StrupatForm</RootNamespace>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<WarningsAsErrors>Nullable</WarningsAsErrors>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Humanizer" Version="3.0.10" />
		<PackageReference Include="OneOf" Version="3.0.271" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Grammar\Grammar.csproj" />
	</ItemGroup>

</Project>
